language: objective-c

branches:
    only:
        - master

before_install:
	- brew update
	- brew upgrade xctool


xcode_project: ZombieCongo.xcodeproj
xcode_scheme: ZombieCongo
xcode_sdk: iphonesimulator7.1
